package name.abhijitsarkar.java.java8impatient.miscellaneous;

/* This class is generated by the name.abhijitsarkar.java.java8impatient.miscellaneous.TestCaseAnnotationProcessor.
 * Do not modify it, it'll be overwritten.
 */
public class TestCaseRunner {
	public static void main(String[] args) {

		int actual = 0;
		actual = name.abhijitsarkar.java.java8impatient.miscellaneous.AnnotatedTests.square1(0);
		if (actual != 0) {
			throw new RuntimeException("Expected 0, but actually " + actual);
		}

		actual = name.abhijitsarkar.java.java8impatient.miscellaneous.AnnotatedTests.square2(2);
		if (actual != 4) {
			throw new RuntimeException("Expected 4, but actually " + actual);
		}

		actual = name.abhijitsarkar.java.java8impatient.miscellaneous.AnnotatedTests.square2(4);
		if (actual != 16) {
			throw new RuntimeException("Expected 16, but actually " + actual);
		}

	}
}