/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AnimatedFrame.java
 *
 * Created on Nov 10, 2011, 6:17:11 PM
 */
package com.github.abhijitsarkar.moviemanager.ui;

import java.awt.Window;

/**
 * 
 * @author abhijit
 */
public class AnimatedFrame extends javax.swing.JFrame {

	private static final long serialVersionUID = 4553712261450477503L;

	/** Creates new form AnimatedFrame */
	public AnimatedFrame(Window w) {
		initComponents();
		setLocationRelativeTo(w);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		animatedPanel = new javax.swing.JPanel();
		waitSpinnerLabel = new javax.swing.JLabel();
		waitLabel = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setAlwaysOnTop(true);
		setEnabled(false);
		setFocusable(false);
		setResizable(false);
		setUndecorated(true);

		animatedPanel.setBorder(new javax.swing.border.SoftBevelBorder(
				javax.swing.border.BevelBorder.RAISED));

		waitSpinnerLabel.setIcon(new javax.swing.ImageIcon(getClass()
				.getResource("/images/spinner1.gif"))); // NOI18N

		waitLabel.setText("Please wait...");

		javax.swing.GroupLayout animatedPanelLayout = new javax.swing.GroupLayout(
				animatedPanel);
		animatedPanel.setLayout(animatedPanelLayout);
		animatedPanelLayout
				.setHorizontalGroup(animatedPanelLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								animatedPanelLayout
										.createSequentialGroup()
										.addContainerGap(58, Short.MAX_VALUE)
										.addGroup(
												animatedPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																animatedPanelLayout
																		.createSequentialGroup()
																		.addComponent(
																				waitSpinnerLabel)
																		.addGap(67,
																				67,
																				67))
														.addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																animatedPanelLayout
																		.createSequentialGroup()
																		.addComponent(
																				waitLabel)
																		.addGap(48,
																				48,
																				48)))));
		animatedPanelLayout.setVerticalGroup(animatedPanelLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						animatedPanelLayout.createSequentialGroup()
								.addContainerGap().addComponent(waitLabel)
								.addGap(22, 22, 22)
								.addComponent(waitSpinnerLabel)
								.addContainerGap(27, Short.MAX_VALUE)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				animatedPanel, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				animatedPanel, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		pack();
	}// </editor-fold>//GEN-END:initComponents
		// Variables declaration - do not modify//GEN-BEGIN:variables

	private javax.swing.JPanel animatedPanel;
	private javax.swing.JLabel waitLabel;
	private javax.swing.JLabel waitSpinnerLabel;
	// End of variables declaration//GEN-END:variables
}
