/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CreateReportPanel.java
 *
 * Created on Nov 8, 2011, 10:38:42 PM
 */
package com.github.abhijitsarkar.moviemanager.ui;

import static com.github.abhijitsarkar.moviemanager.ui.util.UIUtil.createImageIcon;

import java.io.File;

import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

import com.github.abhijitsarkar.moviemanager.ui.eventhandler.MovieReportCreatorTask;
import com.github.abhijitsarkar.moviemanager.ui.util.ConfigManager;
import com.github.abhijitsarkar.moviemanager.ui.util.Image;

/**
 * 
 * @author abhijit
 */
public class CreateReportPanel extends javax.swing.JPanel {

	private static final long serialVersionUID = 9149493603510755866L;

	/** Creates new form CreateReportPanel */
	public CreateReportPanel(JFrame frame) {
		this.frame = frame;

		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		fileChooser = new javax.swing.JFileChooser();
		headerPanel = new javax.swing.JPanel();
		messageLabel = new javax.swing.JLabel(createImageIcon(Image.WARNING));
		inputPanel = new javax.swing.JPanel();
		inputDirLabel = new javax.swing.JLabel();
		inputDirField = new javax.swing.JTextField(30);
		outputFileLabel = new javax.swing.JLabel();
		outputFileField = new javax.swing.JTextField(30);
		inputDirButton = new javax.swing.JButton(createImageIcon(Image.OPEN));
		outputFileButton = new javax.swing.JButton(createImageIcon(Image.SAVE));
		createButton = new javax.swing.JButton(createImageIcon(Image.DOIT));
		closeButton = new javax.swing.JButton(createImageIcon(Image.CLOSE));

		headerPanel.setBorder(new javax.swing.border.SoftBevelBorder(
				javax.swing.border.BevelBorder.RAISED));

		messageLabel.setText("Input directory cannot be empty.");

		javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(
				headerPanel);
		headerPanel.setLayout(headerPanelLayout);
		headerPanelLayout.setHorizontalGroup(headerPanelLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						headerPanelLayout.createSequentialGroup()
								.addComponent(messageLabel)
								.addContainerGap(325, Short.MAX_VALUE)));
		headerPanelLayout.setVerticalGroup(headerPanelLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						headerPanelLayout.createSequentialGroup()
								.addComponent(messageLabel)
								.addContainerGap(15, Short.MAX_VALUE)));

		inputPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(
				new javax.swing.border.SoftBevelBorder(
						javax.swing.border.BevelBorder.RAISED), "Input"));

		inputDirLabel.setText("Input dir:");

		inputDirField
				.getDocument()
				.addDocumentListener(
						new com.github.abhijitsarkar.moviemanager.ui.eventhandler.TextFieldListener(
								inputDirField, outputFileField, createButton,
								messageLabel));

		outputFileLabel.setText("Output file:");

		outputFileField
				.getDocument()
				.addDocumentListener(
						new com.github.abhijitsarkar.moviemanager.ui.eventhandler.TextFieldListener(
								inputDirField, outputFileField, createButton,
								messageLabel));

		inputDirButton.setText("Browse");
		inputDirButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				inputDirButtonActionPerformed(evt);
			}
		});

		outputFileButton.setText("Save");
		outputFileButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				outputFileButtonActionPerformed(evt);
			}
		});

		createButton.setText("Create");
		createButton.setEnabled(false);
		createButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				createButtonActionPerformed(evt);
			}
		});

		closeButton.setText("Close");
		closeButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				closeButtonActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout inputPanelLayout = new javax.swing.GroupLayout(
				inputPanel);
		inputPanel.setLayout(inputPanelLayout);
		inputPanelLayout
				.setHorizontalGroup(inputPanelLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								inputPanelLayout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												inputPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																inputPanelLayout
																		.createSequentialGroup()
																		.addGroup(
																				inputPanelLayout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								inputDirLabel)
																						.addComponent(
																								outputFileLabel))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(
																				inputPanelLayout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								inputPanelLayout
																										.createSequentialGroup()
																										.addComponent(
																												outputFileField,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addGap(18,
																												18,
																												18)
																										.addComponent(
																												outputFileButton,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												115,
																												javax.swing.GroupLayout.PREFERRED_SIZE))
																						.addGroup(
																								inputPanelLayout
																										.createSequentialGroup()
																										.addComponent(
																												inputDirField,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												286,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addGap(18,
																												18,
																												18)
																										.addComponent(
																												inputDirButton,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												115,
																												javax.swing.GroupLayout.PREFERRED_SIZE))))
														.addGroup(
																inputPanelLayout
																		.createSequentialGroup()
																		.addComponent(
																				createButton,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				115,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGap(18,
																				18,
																				18)
																		.addComponent(
																				closeButton,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				115,
																				javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addContainerGap(20, Short.MAX_VALUE)));

		inputPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL,
				new java.awt.Component[] { inputDirField, outputFileField });

		inputPanelLayout
				.setVerticalGroup(inputPanelLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								inputPanelLayout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												inputPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																inputDirField,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																inputDirLabel)
														.addComponent(
																inputDirButton))
										.addGap(18, 18, 18)
										.addGroup(
												inputPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																outputFileField,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																outputFileButton)
														.addComponent(
																outputFileLabel))
										.addGap(38, 38, 38)
										.addGroup(
												inputPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																createButton)
														.addComponent(
																closeButton))
										.addContainerGap(21, Short.MAX_VALUE)));

		inputPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL,
				new java.awt.Component[] { inputDirButton, inputDirField,
						outputFileButton, outputFileField });

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(14, 14, 14)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.CENTER)
												.addComponent(
														headerPanel,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE)
												.addComponent(
														inputPanel,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE))
								.addContainerGap()));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(headerPanel,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(inputPanel,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap()));
	}// </editor-fold>//GEN-END:initComponents

	private void inputDirButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_inputDirButtonActionPerformed
		fileChooser = new JFileChooser(lastOpenedInputDir);
		fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
		int returnVal = fileChooser.showOpenDialog(this);
		if (returnVal == JFileChooser.APPROVE_OPTION) {
			inputDir = fileChooser.getSelectedFile();

			inputDirField.setText(inputDir.getAbsolutePath());
		}
	}// GEN-LAST:event_inputDirButtonActionPerformed

	private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_createButtonActionPerformed
		inputDir = new File(inputDirField.getText());
		outputFile = new File(outputFileField.getText());
		boolean proceed = true;

		if (outputFile.exists()) { // show a warning dialog
			Object[] options = { "Yes", "No" };

			int response = JOptionPane.showOptionDialog(this,
					"File exists; overwrite?", "File exists",
					JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE,
					null, options, options[1]);

			switch (response) {
			case JOptionPane.YES_OPTION:
				outputFileField.setText(outputFile.getAbsolutePath());
				break;
			case JOptionPane.NO_OPTION:
				proceed = false;
				outputFileField.setText("");
				break;
			default:
				proceed = false;
				break;
			}
		}

		if (proceed) {
			ConfigManager.setLastOpenedInputDir(inputDir.getAbsolutePath());
			ConfigManager.setLastOpenedOutputDir(outputFile.getParent());

			createButton.setEnabled(false);

			MovieReportCreatorTask task = new MovieReportCreatorTask(
					createButton, inputDir, outputFile, messageLabel);

			task.execute();
		}
	}// GEN-LAST:event_createButtonActionPerformed

	private void outputFileButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_outputFileButtonActionPerformed
		fileChooser = new JFileChooser(lastOpenedOutputDir);
		fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
		fileChooser.setFileFilter(new FileNameExtensionFilter(
				"Microsoft Excel", "xls", "xlsx"));
		int returnVal = fileChooser.showSaveDialog(this);
		if (returnVal == JFileChooser.APPROVE_OPTION) {
			outputFile = fileChooser.getSelectedFile();

			outputFileField.setText(outputFile.getAbsolutePath());
		}
	}// GEN-LAST:event_outputFileButtonActionPerformed

	private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_closeButtonActionPerformed
		frame.setVisible(false);
		frame.dispose();
	}// GEN-LAST:event_closeButtonActionPerformed
		// Variables declaration - do not modify//GEN-BEGIN:variables

	private javax.swing.JButton closeButton;
	private javax.swing.JButton createButton;
	private javax.swing.JFileChooser fileChooser;
	private javax.swing.JPanel headerPanel;
	private javax.swing.JButton inputDirButton;
	private javax.swing.JTextField inputDirField;
	private javax.swing.JLabel inputDirLabel;
	private javax.swing.JPanel inputPanel;
	private javax.swing.JLabel messageLabel;
	private javax.swing.JButton outputFileButton;
	private javax.swing.JTextField outputFileField;
	private javax.swing.JLabel outputFileLabel;
	// End of variables declaration//GEN-END:variables
	private JFrame frame;
	private File inputDir;
	private File outputFile;
	private String lastOpenedInputDir = ConfigManager.getLastOpenedInputDir();
	private String lastOpenedOutputDir = ConfigManager.getLastOpenedOutputDir();
}
