/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainFrame.java
 *
 * Created on Jun 18, 2011, 12:37:26 AM
 */
package com.github.abhijitsarkar.moviemanager.ui;

import static com.github.abhijitsarkar.moviemanager.ui.util.UIUtil.createImageIcon;

import java.awt.Color;
import java.awt.event.ItemEvent;

import javax.swing.Box;
import javax.swing.ButtonModel;
import javax.swing.JDialog;
import javax.swing.JMenu;
import javax.swing.JPanel;
import javax.swing.border.Border;

import com.github.abhijitsarkar.moviemanager.ui.util.Image;

/**
 * 
 * @author abhijit
 */
public class MainFrame extends javax.swing.JFrame {

	private static final long serialVersionUID = -2819809062384909757L;

	/** Creates new form MainFrame */
	public MainFrame() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		tabbedPane = new javax.swing.JTabbedPane();
		menuBar = new javax.swing.JMenuBar();
		settingsMenu = new javax.swing.JMenu();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("Movie Manager");
		setName("rootFrame"); // NOI18N
		setResizable(false);

		tabbedPane.add("Create Report", createReportPanel);

		menuBar.add(Box.createHorizontalGlue());

		settingsMenu.setIcon(createImageIcon(Image.SETTINGS));
		defaultMenuBorder = settingsMenu.getBorder();
		settingsMenu.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseEntered(java.awt.event.MouseEvent evt) {
				settingsMenuMouseEntered(evt);
			}

			public void mouseExited(java.awt.event.MouseEvent evt) {
				settingsMenuMouseExited(evt);
			}
		});
		settingsMenu.addItemListener(new java.awt.event.ItemListener() {
			public void itemStateChanged(java.awt.event.ItemEvent evt) {
				settingsMenuItemStateChanged(evt);
			}
		});
		menuBar.add(settingsMenu);

		setJMenuBar(menuBar);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				tabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 29,
				Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				tabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.PREFERRED_SIZE));

		pack();
		java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit()
				.getScreenSize();
		java.awt.Dimension dialogSize = getSize();
		setLocation((screenSize.width - dialogSize.width) / 2,
				(screenSize.height - dialogSize.height) / 2);
	}// </editor-fold>//GEN-END:initComponents

	private void settingsMenuItemStateChanged(java.awt.event.ItemEvent evt) {// GEN-FIRST:event_settingsMenuItemStateChanged
		JMenu menu = (JMenu) evt.getSource();
		ButtonModel model = menu.getModel();

		if (evt.getStateChange() == ItemEvent.SELECTED) {
			model.setArmed(true);
			model.setPressed(true);

			settingsDialog = new SettingsDialog(evt.getSource(),
					defaultMenuBorder);
			settingsDialog.setLocationRelativeTo(this);
			settingsDialog.setVisible(true);
		} else {
			model.setArmed(false);
			model.setPressed(false);
		}
	}// GEN-LAST:event_settingsMenuItemStateChanged

	private void settingsMenuMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_settingsMenuMouseEntered
		JMenu menu = (JMenu) evt.getComponent();
		menu.setBorder(dashedLineBorder);
	}// GEN-LAST:event_settingsMenuMouseEntered

	private void settingsMenuMouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_settingsMenuMouseExited
		JMenu menu = (JMenu) evt.getComponent();
		menu.setBorder(defaultMenuBorder);
	}// GEN-LAST:event_settingsMenuMouseExited

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JMenuBar menuBar;
	private javax.swing.JMenu settingsMenu;
	private javax.swing.JTabbedPane tabbedPane;
	// End of variables declaration//GEN-END:variables
	private JPanel createReportPanel = new CreateReportPanel(this);
	private JDialog settingsDialog = null;
	private static final Border dashedLineBorder = new DashedLineBorder(
			Color.BLACK, 1);
	private Border defaultMenuBorder = null;
}
